yarnPath: .yarn/releases/yarn-4.0.0-rc.20.cjs

supportedArchitectures:
    os:
        - current
        - darwin
        - linux
        - win32
    cpu:
        - current
        - ia32
        - x64
        - arm64
